### PR TITLE
Constructors & Files

### PR DESCRIPTION
**Pull request by Acquized**
I added a Constructor that allows to initalize the ItemBuilder with a ItemStack from a Config.
I also added the Method `toConfig()` and `fromConfig()` to write or read the ItemStack from the Config. The fromConfig Method returns a complete new ItemBuilder Instance.

Tagging here @Kev575 - i want to hear your opinion about this update. Everyone is also welcome to leave your opinion about this Feature here.

### CODE REVIEW

**Comment by Kev575** [comment]
I like it :D
Maybe add an integrated (de-)serializer to and from Json using Google's Gson Library.

**Comment by Acquized** [comment]
Could add `fromJson` and `toJson`, but i will need a few Days to implement it because i just got a new computer.

**Comment by Kev575** [comment]
No problem, I could do that tomorrow ;)

**Comment by Acquized** [comment]
Would be very friendly. I love how you contribute to this project. May i add you as contributor? This will allow you to push directly into the master branch.

**EDIT**: I added you as contributor, but when you push something into the project, please push it to the dev branch as the master branch contains the code that is published on the Spigot Page.

**Comment by Kev575** [comment]
Thank you :) You're welcome!
I'll do so. This project is really cool, I use it in many projects.
Before that I used a method like item(Material material, String displayname, String[] lores boolean unbreakable, int data, int amount). In the most cases this work(s/ed) fine for me, but when I have to build an item often, only need material and lores or add lores later, I need to use this to not stuck in too much duplicated code. :D

**Comment by Acquized** [comment]
I don't know the Spigot shaded libs, is gson by default shaded into the jar or was it first included in 1.9/1.8?

**Comment by Kev575** [comment]
Gson is included by default from 1.7 i guess...

**Comment by Acquized** [comment]
Alright, going to merge it after i pushed the reworked Javadocs.

**Comment by Acquized** [comment]
Actually the branch `dev` contains conflicts with `master`, fixed it on my local machine, pushing with reworked javadocs and new source to master tonight.

**Comment by Acquized** [comment]
Looks like the Branch conflicts with the master branch, going to commit the changes directly into the master branch.

**Pull request closed without merging**
